### ISSUE TITLE
Error while training. Configuration mismatch. 

### ISSUE THREAD

**Issue by zaverichintan** [magnux/MotionGAN#2]
I generated the h5 data file and tried to run train.py. I am getting following error:

`2019-10-23 17:15:37.070515: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
| ep: 0 | lr: 1.00e-03 |:   0%|          | 0/512 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 128, in <module>
    losses = model_wrap.disc_train(disc_inputs + gen_inputs + place_holders)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Endpoint "real_seq:0" fed more than once.`

I am using following stack:
python 2.7.17
tensorflow 1.12.0

Let me know your configuration ? Thanks.

**Comment by ywh0703** [comment]
> I generated the h5 data file and tried to run train.py. I am getting following error:
> 
> ```
> 2019-10-23 17:15:37.070515: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
> | ep: 0 | lr: 1.00e-03 |:   0%|          | 0/512 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "train.py", line 128, in <module>
>     losses = model_wrap.disc_train(disc_inputs + gen_inputs + place_holders)
> .
> .
> .
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Endpoint "real_seq:0" fed more than once.
> ```
> 
> I am using following stack: python 2.7.17 tensorflow 1.12.0
> 
> Let me know your configuration ? Thanks.

Hello, I want to know how you generate H5 files, and you will report an IO error when running a file
